const db = require('./config/db');

// Clear existing products first
db.query('DELETE FROM products', () => {
  console.log('Cleared existing products');

  const products = [

    // ─── GYNAECOLOGY (category_id: 1) ───
    { name: 'PASIVIT', sku: 'MP-GY-001', category_id: 1, sub_category: 'Multivitamin', composition: 'Multivitamin, Multimineral & Lycopene', pack_size: 'Capsules / Syrup', description: 'A comprehensive multivitamin and multimineral supplement with lycopene, supporting overall nutritional health for women.' },
    { name: 'HERBATONE-G', sku: 'MP-GY-002', category_id: 1, sub_category: 'Herbal Uterine', composition: 'Herbal Uterine Tonic', pack_size: 'Syrup', description: 'Herbal uterine tonic for supporting uterine health and hormonal balance in women.' },
    { name: 'OVALIFT', sku: 'MP-GY-003', category_id: 1, sub_category: 'Fertility Support', composition: 'L-Arginine + Myo Inositol + Folic Acid + Vitamin B12 + Vitamin B6 + Selenium + Minerals with Micronutrients', pack_size: 'Tablets', description: 'Comprehensive fertility support with L-Arginine, Myo Inositol and essential vitamins for hormonal balance and reproductive health.' },
    { name: 'OVALIFT-M', sku: 'MP-GY-004', category_id: 1, sub_category: 'PCOS Management', composition: 'Myo-Inositol 600 mg + Metformin Hydrochloride (SR) 500 mg', pack_size: 'Tablets', description: 'Combination of Myo-Inositol and Metformin for effective PCOS management and insulin sensitisation.' },
    { name: 'OVALIFT Q10', sku: 'MP-GY-005', category_id: 1, sub_category: 'Fertility Support', composition: 'Myo-Inositol 550 mg + D-Chiro-Inositol 13.8 mg + L-Methylfolate 0.5 mcg + Mecobalamin 750 mcg + L-Arginine 10 mg + Co-enzyme Q10 100 mg', pack_size: 'Tablets', description: 'Advanced fertility formulation with CoQ10 and inositol complex to improve oocyte quality and ovarian reserve.' },
    { name: 'PASSLACT', sku: 'MP-GY-006', category_id: 1, sub_category: 'Lactation Support', composition: 'Shatavari 200 mg + Methi 200 mg + Vidarikand 100 mg + Usgira 100 mg + Patha 50 mg + Jeerak 50 mg + Ashwagandha 100 mg + Mulethi 100 mg + Lehsun 50 mg + Haldi 50 mg', pack_size: 'Capsules', description: 'Herbal galactagogue formulation to support lactation and milk production in nursing mothers.', specification: 'Shatavari 200 mg\nMethi 200 mg\nVidarikand 100 mg\nUsgira 100 mg\nPatha 50 mg\nJeerak 50 mg\nAshwagandha 100 mg\nMulethi 100 mg\nLehsun 50 mg\nHaldi 50 mg' },
    { name: 'PASCAN-V', sku: 'MP-GY-007', category_id: 1, sub_category: 'Antifungal / Antiprotozoal', composition: 'Clotrimazole 200 mg + Tinidazole 600 mg + Povidone Iodine 200 mg', pack_size: 'Tablets', description: 'Broad-spectrum antifungal and antiprotozoal combination for vaginal infections.' },
    { name: 'PASTATE-MF', sku: 'MP-GY-008', category_id: 1, sub_category: 'Menorrhagia', composition: 'Tranexamic Acid 500 mg + Mefenamic Acid 250 mg', pack_size: 'Tablets', description: 'Combination of antifibrinolytic and NSAID for management of heavy menstrual bleeding and associated pain.' },
    { name: 'GLOBIN-Z', sku: 'MP-GY-009', category_id: 1, sub_category: 'Iron / Antioxidant', composition: 'Carbonyl Iron 100 mg + Folic Acid 1.5 mg + Zinc 40 mg + Vit. C 75 mg + Vit. B12 15 mcg', pack_size: 'Capsules / Suspension', description: 'Iron supplement with zinc and vitamins for anaemia management and nutritional support during pregnancy.' },
    { name: 'DOXY-NVP', sku: 'MP-GY-010', category_id: 1, sub_category: 'Nausea / Vomiting', composition: 'Doxylamine Succinate 10 mg + Folic Acid 2.5 mg + Pyridoxine HCl 10 mg', pack_size: 'Tablets', description: 'Safe and effective treatment for nausea and vomiting during pregnancy (NVP).' },
    { name: 'NUTRO', sku: 'MP-GY-011', category_id: 1, sub_category: 'Protein & Nutrition', composition: 'Protein, Carbohydrate, Vitamins & Essential Minerals', pack_size: 'Protein Powder', description: 'High-protein nutritional supplement with carbohydrates and essential minerals for maternal and general health support.' },
    { name: 'PASCAL', sku: 'MP-GY-012', category_id: 1, sub_category: 'Calcium Supplement', composition: 'Calcium Citrate 1000 mg + Vitamin D3 200 I.U. + Magnesium 100 mg + Zinc 25 mg', pack_size: 'Suspension / Tablets', description: 'Complete calcium supplement with Vitamin D3, magnesium and zinc for bone health during pregnancy and lactation.' },
    { name: 'TRICHOFOL', sku: 'MP-GY-013', category_id: 1, sub_category: 'Hair & Micronutrient', composition: 'Biotin USP 10 mg + N-Acetyl Cysteine USP 50 mg + Calcium Pantothenate IP 100 mg + Sodium Selenite USP 65 mcg + Cupric Oxide IP 3 mg + Zinc Oxide IP 22.5 mg', pack_size: 'Tablets / Hair Oil / Shampoo', description: 'Micronutrient complex with biotin, zinc and selenium for hair growth and overall nutritional support.' },
    { name: 'PASFOL-79', sku: 'MP-GY-014', category_id: 1, sub_category: 'Folic Acid Supplement', composition: 'Biotin 5 mg + Folic Acid 5 mg', pack_size: 'Tablets', description: 'High-dose folic acid with biotin for neural tube defect prevention and hair health support.' },
    { name: 'IROPAS-XT', sku: 'MP-GY-015', category_id: 1, sub_category: 'Iron Supplement', composition: 'Ferrous Ascorbate 100 mg + Folic Acid 1.5 mg + Zinc Sulphate 22.5 mg', pack_size: 'Tablets', description: 'Highly bioavailable iron supplement with folic acid and zinc for treatment and prevention of iron deficiency anaemia.' },
    { name: 'PAS GEL', sku: 'MP-GY-016', category_id: 1, sub_category: 'Topical Analgesic', composition: 'Diclofenac Diethylamine 1.16% w/w + Oleum Lini 3% w/w + Methyl Salicylate 10% w/w + Menthol 5% w/w', pack_size: 'Gel', description: 'Topical anti-inflammatory and analgesic gel for joint and muscle pain relief.' },

    // ─── GENERAL PRACTICE (category_id: 3) ───
    // Anti-Allergic / Anti-Cough
    { name: 'MUCOSET', sku: 'MP-GP-001', category_id: 3, sub_category: 'Anti-Allergic / Anti-Cough', composition: 'N-Acetyl L-Cysteine 600 mg + Acebrophylline 100 mg', pack_size: 'Tablets', description: 'Mucolytic and bronchodilator combination for productive cough and obstructive airway conditions.' },
    { name: 'PASTRIN-COLD+', sku: 'MP-GP-002', category_id: 3, sub_category: 'Anti-Allergic / Anti-Cough', composition: 'Paracetamol 500 mg + Phenylephrine HCl 5 mg + Caffeine 30 mg + Diphenhydramine HCl 25 mg (Tablets) / Paracetamol 250 mg + Phenylephrine 5 mg + Sodium Citrate 120 mg + CPM 2 mg (Syrup)', pack_size: 'Tablets / Syrup', description: 'Multi-action cold and fever formulation with analgesic, decongestant, antihistamine and caffeine.' },
    { name: 'PACET-L', sku: 'MP-GP-003', category_id: 3, sub_category: 'Anti-Allergic / Anti-Cough', composition: 'Levocetirizine 10 mg', pack_size: 'Tablets', description: 'Second-generation antihistamine for allergic rhinitis, urticaria and other allergic conditions.' },
    { name: 'PASKOF-A', sku: 'MP-GP-004', category_id: 3, sub_category: 'Anti-Allergic / Anti-Cough', composition: 'Ambroxol 15 mg + Terbutaline 1.25 mg + Guaiphenesin 50 mg + Menthol 10 mg per 5 ml', pack_size: 'Cough Syrup', description: 'Triple-action cough syrup with mucolytic, bronchodilator and expectorant for productive cough and bronchitis.' },
    { name: 'PASKOF-D', sku: 'MP-GP-005', category_id: 3, sub_category: 'Anti-Allergic / Anti-Cough', composition: 'Dextromethorphan 15 mg + Phenylephrine 5 mg + Chlorpheniramine 2 mg', pack_size: 'Syrup', description: 'Combination antitussive, decongestant and antihistamine for dry cough and upper respiratory infections.' },
    { name: 'PASKOF-LS', sku: 'MP-GP-006', category_id: 3, sub_category: 'Anti-Allergic / Anti-Cough', composition: 'Levosalbutamol 1 mg + Guaiphenesin 50 mg + Ambroxol 15 mg per 5 ml', pack_size: 'Syrup', description: 'Bronchodilator and mucolytic combination for asthma, bronchitis and obstructive airway disease.' },
    { name: 'PACET-LM', sku: 'MP-GP-007', category_id: 3, sub_category: 'Anti-Allergic / Anti-Cough', composition: 'Montelukast Sodium 10 mg + Levocetirizine 5 mg', pack_size: 'Tablets', description: 'Leukotriene antagonist and antihistamine combination for allergic rhinitis and asthma management.' },
    { name: 'PASFEX-M', sku: 'MP-GP-008', category_id: 3, sub_category: 'Anti-Allergic / Anti-Cough', composition: 'Fexofenadine 120 mg + Montelukast Sodium 10 mg', pack_size: 'Tablets', description: 'Non-sedating antihistamine with leukotriene antagonist for chronic allergic rhinitis and urticaria.' },
    // Anti-Ulcerants
    { name: 'PASZOLE-D', sku: 'MP-GP-009', category_id: 3, sub_category: 'Anti-Ulcerants', composition: 'Omeprazole 20 mg + Domperidone 10 mg', pack_size: 'Capsules', description: 'Proton pump inhibitor with prokinetic for GERD, peptic ulcer and gastric motility disorders.' },
    { name: 'PASPAN', sku: 'MP-GP-010', category_id: 3, sub_category: 'Anti-Ulcerants', composition: 'Pantaprazole 40 mg', pack_size: 'Tablets / Injection', description: 'Potent proton pump inhibitor for acid-related disorders including GERD, peptic ulcer and Zollinger-Ellison syndrome.' },
    { name: 'PASPAN-DSR', sku: 'MP-GP-011', category_id: 3, sub_category: 'Anti-Ulcerants', composition: 'Pantoprazole 40 mg + Domperidone 30 mg SR', pack_size: 'Capsules', description: 'Sustained-release combination of pantoprazole and domperidone for reflux oesophagitis and functional dyspepsia.' },
    { name: 'CAINGEL', sku: 'MP-GP-012', category_id: 3, sub_category: 'Anti-Ulcerants', composition: 'Magaldrate 540 mg + Simethicone 50 mg + Oxetacaine 10 mg', pack_size: 'Suspension', description: 'Fast-acting antacid with local anaesthetic and antiflatulent for hyperacidity, ulcer pain and bloating.' },
    // Anti-Microbials / Anti-Infectives
    { name: 'AZIDIK', sku: 'MP-GP-013', category_id: 3, sub_category: 'Anti-Microbials', composition: 'Azithromycin 500 mg', pack_size: 'Tablets', description: 'Macrolide antibiotic for respiratory tract infections, skin infections and sexually transmitted diseases.' },
    { name: 'PASFLOX-OZ', sku: 'MP-GP-014', category_id: 3, sub_category: 'Anti-Microbials', composition: 'Ofloxacin 200 mg + Ornidazole 500 mg', pack_size: 'Tablets', description: 'Fluoroquinolone and antiprotozoal combination for mixed bacterial and protozoal infections of the GI tract.' },
    { name: 'DOXYPAS-LB', sku: 'MP-GP-015', category_id: 3, sub_category: 'Anti-Microbials', composition: 'Doxycycline 100 mg + Lactobacillus 5 Billion spores', pack_size: 'Tablets', description: 'Broad-spectrum tetracycline antibiotic with probiotic to prevent antibiotic-associated diarrhoea.' },
    { name: 'MEDICEF-O PLUS', sku: 'MP-GP-016', category_id: 3, sub_category: 'Anti-Microbials', composition: 'Cefixime 200 mg + Ofloxacin 200 mg', pack_size: 'Tablets', description: 'Third-generation cephalosporin with fluoroquinolone for complicated urinary tract and respiratory infections.' },
    { name: 'PASCLOX-CV-625', sku: 'MP-GP-017', category_id: 3, sub_category: 'Anti-Microbials', composition: 'Amoxycillin 500 mg + Clavulanic Acid 125 mg', pack_size: 'Tablets', description: 'Beta-lactam antibiotic with beta-lactamase inhibitor for resistant respiratory, urinary and skin infections.' },
    { name: 'PROFLO', sku: 'MP-GP-018', category_id: 3, sub_category: 'Anti-Microbials', composition: 'Pre & Probiotics Effervescent', pack_size: 'Effervescent Tablets', description: 'Prebiotic and probiotic combination for gut microbiome restoration and gastrointestinal health.' },
    { name: 'NEUROPAS', sku: 'MP-GP-019', category_id: 3, sub_category: 'Anti-Microbials', composition: 'Methylcobalamin 2500 mcg', pack_size: 'Injection', description: 'High-dose methylcobalamin injection for peripheral neuropathy, vitamin B12 deficiency and nerve regeneration.' },
    { name: 'NEUROPAS-AL', sku: 'MP-GP-020', category_id: 3, sub_category: 'Antioxidants / Vitamins', composition: 'Lycopene 6000 mcg + Methylcobalamin 1500 mcg + Alpha Lipoic Acid 100 mg + Vitamin A + Vit. C + Vit. E + Folic Acid', pack_size: 'Capsules', description: 'Comprehensive antioxidant and neuroprotective supplement with lycopene, ALA and methylcobalamin.' },
    // Anti-Inflammatories / Analgesics
    { name: 'NIMPAS-DS', sku: 'MP-GP-021', category_id: 3, sub_category: 'Anti-Inflammatories / Analgesics', composition: 'Paracetamol 250 mg per 5 ml', pack_size: 'Suspension', description: 'Paediatric paracetamol suspension for fever and mild to moderate pain in children.' },
    { name: 'PACY-P', sku: 'MP-GP-022', category_id: 3, sub_category: 'Anti-Inflammatories / Analgesics', composition: 'Aceclofenac 100 mg + Paracetamol 325 mg', pack_size: 'Tablets', description: 'NSAID and analgesic combination for pain and inflammation in arthritis, post-operative and musculoskeletal conditions.' },
    { name: 'PACY-SP', sku: 'MP-GP-023', category_id: 3, sub_category: 'Anti-Inflammatories / Analgesics', composition: 'Aceclofenac 100 mg + Paracetamol 325 mg + Serratiopeptidase 15 mg', pack_size: 'Tablets', description: 'Triple combination with proteolytic enzyme for enhanced anti-inflammatory and analgesic effect in acute pain.' },
    { name: 'SANTRIN', sku: 'MP-GP-024', category_id: 3, sub_category: 'Anti-Inflammatories / Analgesics', composition: 'Nimesulide 100 mg + Paracetamol 325 mg', pack_size: 'Tablets', description: 'COX-2 preferential NSAID with paracetamol for acute pain, fever and inflammatory conditions.' },
    { name: 'BETAPAST', sku: 'MP-GP-025', category_id: 3, sub_category: 'Anti-Inflammatories / Analgesics', composition: 'Betahistine 8 mg / 16 mg', pack_size: 'Tablets', description: 'Histamine analogue for vertigo, tinnitus and Meniere\'s disease management.' },
    // Antioxidants / Iron / Calcium
    { name: 'IROPAS-XT (GP)', sku: 'MP-GP-026', category_id: 3, sub_category: 'Antioxidants / Iron / Calcium', composition: 'Ferrous Ascorbate 100 mg + Folic Acid 1.5 mg + Zinc Sulphate 22.5 mg', pack_size: 'Tablets', description: 'Highly bioavailable iron with folic acid and zinc for anaemia in general practice.' },
    { name: 'GLOBIN-Z (GP)', sku: 'MP-GP-027', category_id: 3, sub_category: 'Antioxidants / Iron / Calcium', composition: 'Carbonyl Iron 100 mg + Folic Acid 1.5 mg + Zinc 40 mg + Vit. C 75 mg + Vit. B12 15 mcg', pack_size: 'Capsules / Suspension', description: 'Carbonyl iron with antioxidant vitamins and zinc for treatment of iron deficiency and nutritional anaemia.' },

    // ─── DERMATOLOGY / SKIN RANGE (category_id: 4) ───
    { name: 'TRICHOFOL Tablets', sku: 'MP-DV-001', category_id: 4, sub_category: 'Hair Care', composition: 'Biotin 10 mg + N-Acetyl Cysteine 50 mg + Calcium Pantothenate 100 mg + Sodium Selenate 65 mcg + Cupric Oxide 3 mg + Zinc Oxide 22.5 mg', pack_size: 'Tablets', description: 'Micronutrient supplement for hair loss, brittle nails and scalp health.' },
    { name: 'TRICHOFOL Hair Oil', sku: 'MP-DV-002', category_id: 4, sub_category: 'Hair Care', composition: 'Ayurvedic Oil For Hair Problems', pack_size: 'Hair Oil', description: 'Ayurvedic hair oil with natural herbs for nourishment, strengthening and reducing hair fall.' },
    { name: 'TRICHOFOL Shampoo', sku: 'MP-DV-003', category_id: 4, sub_category: 'Hair Care', composition: 'Ayurvedic Formula For Hair Problems', pack_size: 'Shampoo', description: 'Herbal shampoo for dandruff control, scalp cleansing and hair fall prevention.' },
    { name: 'FACEPIC Gel', sku: 'MP-DV-004', category_id: 4, sub_category: 'Anti-Acne', composition: 'Clindamycin Phosphate 1% w/w + Nicotinamide 4% w/w', pack_size: 'Gel', description: 'Antibiotic and niacinamide gel for acne vulgaris, reducing inflammation and sebum production.' },
    { name: 'FACEPIC Soap', sku: 'MP-DV-005', category_id: 4, sub_category: 'Anti-Acne', composition: 'Ayurvedic Soap with 21 Herbs', pack_size: 'Soap', description: 'Herbal soap formulated with 21 Ayurvedic ingredients for cleansing acne-prone and sensitive skin.' },
    { name: 'KETOKANAZ', sku: 'MP-DV-006', category_id: 4, sub_category: 'Anti-Dandruff / Antifungal', composition: 'Ketoconazole + Aloe Vera + Vitamin E + Zinc', pack_size: 'Shampoo / Soap', description: 'Antifungal shampoo and soap with aloe vera and vitamin E for dandruff, seborrhoeic dermatitis and scalp infections.' },
    { name: 'PASMET', sku: 'MP-DV-007', category_id: 4, sub_category: 'Corticosteroid', composition: 'Mometasone Furoate 0.1%', pack_size: 'Cream', description: 'Potent topical corticosteroid for eczema, psoriasis, allergic dermatitis and inflammatory skin conditions.' },
    { name: 'SKINCLOB-SF', sku: 'MP-DV-008', category_id: 4, sub_category: 'Corticosteroid', composition: 'Clobetasol 0.05% w/w + Salicylic Acid 3% w/w', pack_size: 'Cream', description: 'Super-potent corticosteroid with keratolytic for chronic plaque psoriasis and resistant dermatoses.' },
    { name: 'SOPHNER', sku: 'MP-DV-009', category_id: 4, sub_category: 'Moisturizers', composition: 'White Soft Paraffin 15.0% w/w + Liquid Paraffin 6.0% w/w', pack_size: 'Cream', description: 'Emollient moisturiser for dry, flaky and ichthyotic skin conditions providing intensive barrier protection.' },
    { name: 'LULIKANAZ', sku: 'MP-DV-010', category_id: 4, sub_category: 'Anti-Fungal', composition: 'Luliconazole 1%', pack_size: 'Cream & Lotion', description: 'Broad-spectrum antifungal for tinea corporis, tinea cruris, tinea pedis and other dermatophyte infections.' },
    { name: 'IT-MASTER', sku: 'MP-DV-011', category_id: 4, sub_category: 'Anti-Fungal', composition: 'Itraconazole 100 mg', pack_size: 'Capsule', description: 'Oral triazole antifungal for systemic and deep fungal infections including onychomycosis.' },
    { name: 'REMESSCAB', sku: 'MP-DV-012', category_id: 4, sub_category: 'Anti-Parasitic', composition: 'Permethrin 5% w/v', pack_size: 'Lotion & Soap', description: 'Topical permethrin for scabies and pediculosis (lice) treatment and eradication.' },
  ];

  let done = 0;
  products.forEach(p => {
    db.query('INSERT INTO products SET ?', p, (err, r) => {
      if (err) console.log('ERR:', p.sku, '-', err.message);
      else console.log('OK:', p.name, '| id:', r.insertId);
      if (++done === products.length) {
        console.log('\nAll products seeded successfully!');
        process.exit();
      }
    });
  });
});
