const db = require('./config/db');

db.query("DELETE FROM products WHERE sku NOT LIKE 'MP-%'", () => {
  const products = [
    {name:'OvaCycle Tablets',sku:'MP-GY-001',category_id:1,sub_category:'PCOS Management',description:'Scientifically formulated with Myo-Inositol, D-Chiro-Inositol and phytoestrogens to restore hormonal balance, regulate menstrual cycles and improve insulin sensitivity in PCOS patients.',composition:'Myo-Inositol 2g + D-Chiro-Inositol 50mg + Folic Acid 400mcg',pack_size:'30 Tablets/Strip',indication:'PCOS, Irregular Periods, Hormonal Imbalance'},
    {name:'FemGuard Capsules',sku:'MP-GY-002',category_id:1,sub_category:'Vaginal Health',description:'Probiotic-rich formula with Lactobacillus strains, cranberry extract and zinc for maintaining healthy vaginal flora, preventing recurrent UTIs and reducing discharge.',composition:'Lactobacillus acidophilus 5B CFU + Cranberry Extract 200mg + Zinc 10mg',pack_size:'10 Capsules/Strip',indication:'Vaginal Infections, Recurrent UTI, Dysbiosis'},
    {name:'GestaCare Syrup',sku:'MP-GY-003',category_id:1,sub_category:'Prenatal Nutrition',description:'Iron-folic acid combination with DHA, B-complex and trace minerals developed for complete maternal and foetal nutrition from conception through lactation.',composition:'Iron Polymaltose 100mg + Folic Acid 5mg + DHA 200mg + Vitamins B6/B12/C',pack_size:'200 mL Bottle',indication:'Anaemia in Pregnancy, Prenatal Supplementation'},
    {name:'MenoPro Tablets',sku:'MP-GY-004',category_id:1,sub_category:'Menopause Management',description:'Non-hormonal relief for perimenopausal symptoms using standardised red clover isoflavones, black cohosh and evening primrose oil.',composition:'Red Clover Isoflavones 40mg + Black Cohosh 20mg + Evening Primrose Oil 500mg',pack_size:'30 Tablets/Strip',indication:'Menopause, Perimenopause, Hot Flashes'},
    {name:'FertiCare Soft Gels',sku:'MP-GY-005',category_id:1,sub_category:'Fertility Support',description:'CoQ10-enriched antioxidant formula combining L-Carnitine, Vitamin E and selenium to improve oocyte quality and support implantation success.',composition:'CoQ10 200mg + L-Carnitine 500mg + Vitamin E 400IU + Selenium 75mcg',pack_size:'30 Soft Gels/Strip',indication:'Infertility, Poor Ovarian Reserve, IVF Support'},
    {name:'OsteoMax Tablets',sku:'MP-OR-001',category_id:2,sub_category:'Bone Density',description:'High-bioavailability calcium carbonate paired with Vitamin D3 and K2-MK7 to enhance calcium absorption and reduce fracture risk in osteoporosis patients.',composition:'Calcium Carbonate 1250mg + Vitamin D3 1000IU + K2-MK7 90mcg',pack_size:'30 Tablets/Strip',indication:'Osteoporosis, Osteopenia, Post-menopausal Calcium Deficiency'},
    {name:'FlexiJoint Gel',sku:'MP-OR-002',category_id:2,sub_category:'Joint Pain Relief',description:'Diclofenac-based topical NSAID gel with methyl salicylate and linseed oil for fast-acting, targeted relief from arthritis, sports injuries and myalgia.',composition:'Diclofenac Diethylamine 1.16% + Methyl Salicylate 10% + Linseed Oil 3%',pack_size:'50g Tube',indication:'Osteoarthritis, Sports Injuries, Myalgia, Sprains'},
    {name:'CalciPlus Syrup',sku:'MP-OR-003',category_id:2,sub_category:'Calcium Supplement',description:'Palatable syrup combining Calcium Gluconate with Vitamin D3 and zinc, ideal for paediatric patients and elderly requiring bone nourishment.',composition:'Calcium Gluconate 115mg/5mL + Vitamin D3 400IU + Zinc Sulphate 10mg',pack_size:'200mL Bottle',indication:'Calcium Deficiency, Rickets, Growth Supplementation'},
    {name:'ArthroEase Capsules',sku:'MP-OR-004',category_id:2,sub_category:'Arthritis Management',description:'Disease-modifying nutraceutical combining Glucosamine, Chondroitin and Boswellia extract to rebuild cartilage matrix and reduce pro-inflammatory cytokines.',composition:'Glucosamine Sulphate 500mg + Chondroitin Sulphate 400mg + Boswellia 200mg',pack_size:'30 Capsules/Strip',indication:'Osteoarthritis, Cartilage Degeneration, Joint Space Narrowing'},
    {name:'ImmunoShield Syrup',sku:'MP-GP-001',category_id:3,sub_category:'Immunity',description:'Potent immunity-boosting syrup with Zinc, Vitamin C, Elderberry extract and Echinacea standardised extracts.',composition:'Zinc Sulphate 20mg + Vitamin C 500mg + Elderberry Extract 150mg + Echinacea 100mg',pack_size:'200mL Bottle',indication:'Recurrent Infections, Post-viral Recovery, Immunity Maintenance'},
    {name:'VitaMax Tablets',sku:'MP-GP-002',category_id:3,sub_category:'Multivitamin',description:'Comprehensive A-Z multivitamin and mineral formula covering all essential micronutrients for daily nutritional insurance.',composition:'Vitamin A-E, B-Complex, C + Iron 14mg + Zinc 8mg + Selenium + Chromium',pack_size:'30 Tablets/Strip',indication:'Nutritional Deficiencies, General Debility, Convalescence'},
    {name:'CoughXpel Syrup',sku:'MP-GP-003',category_id:3,sub_category:'Respiratory',description:'Triple-action cough formulation combining Ambroxol, Guaifenesin and Terbutaline for productive cough, bronchitis and URTI management.',composition:'Ambroxol 15mg + Guaifenesin 100mg + Terbutaline 1.25mg per 5mL',pack_size:'100mL Bottle',indication:'Productive Cough, Bronchitis, URTI, Asthma Adjuvant'},
    {name:'AcidGone Suspension',sku:'MP-GP-004',category_id:3,sub_category:'GI Care',description:'Fast-acting antacid suspension for rapid neutralisation of excess gastric acid and elimination of flatulence.',composition:'Aluminium Hydroxide 250mg + Magnesium Hydroxide 250mg + Simethicone 50mg per 5mL',pack_size:'170mL Bottle',indication:'Hyperacidity, GERD, Peptic Ulcer, Flatulence'},
    {name:'AcneClear Gel',sku:'MP-DV-001',category_id:4,sub_category:'Anti-Acne',description:'Lightweight, non-comedogenic gel combining Salicylic Acid and Niacinamide to exfoliate pores, reduce sebum and calm post-acne erythema.',composition:'Salicylic Acid 2% + Niacinamide 4% + Allantoin 0.5%',pack_size:'30g Tube',indication:'Acne Vulgaris, Comedones, Oily Skin'},
    {name:'PoreReset Face Wash',sku:'MP-DV-002',category_id:4,sub_category:'Anti-Acne',description:'SLS-free foaming cleanser with Tea Tree Oil and Zinc PCA for deep cleansing of acne-prone skin without disrupting the skin barrier.',composition:'Tea Tree Oil 0.5% + Zinc PCA 1% + Glycerin 5%',pack_size:'100mL Pump',indication:'Oily/Acne-prone Skin, Enlarged Pores'},
    {name:'HydraLock Cream',sku:'MP-DV-003',category_id:4,sub_category:'Moisturizers',description:'Ceramide-enriched rich moisturiser with Hyaluronic Acid and Shea Butter for intensive hydration and barrier repair.',composition:'Ceramides NP/AP/EOP 0.5% + Hyaluronic Acid 1% + Shea Butter 10%',pack_size:'50g Jar',indication:'Dry Skin, Atopic Dermatitis, Barrier Dysfunction'},
    {name:'SoftSkin Body Lotion',sku:'MP-DV-004',category_id:4,sub_category:'Moisturizers',description:'Urea-based body lotion with Lactic Acid and Glycerin for deep moisturisation of very dry, rough and flaky skin.',composition:'Urea 10% + Lactic Acid 5% + Glycerin 10%',pack_size:'200mL Bottle',indication:'Xerosis, Ichthyosis, Keratosis Pilaris'},
    {name:'FungiStop Cream',sku:'MP-DV-005',category_id:4,sub_category:'Anti-Fungal',description:'Broad-spectrum antifungal cream combining Clotrimazole and Beclomethasone for rapid resolution of dermatophyte and candidal infections.',composition:'Clotrimazole 1% + Beclomethasone Dipropionate 0.025%',pack_size:'30g Tube',indication:'Tinea Corporis, Tinea Cruris, Candidiasis'},
    {name:'TineaCure Solution',sku:'MP-DV-006',category_id:4,sub_category:'Anti-Fungal',description:'Topical solution for scalp tinea and onychomycosis with Fluconazole and DMSO vehicle for enhanced nail and scalp penetration.',composition:'Fluconazole 1% + DMSO 10% in Isopropyl Alcohol',pack_size:'30mL Bottle',indication:'Tinea Capitis, Onychomycosis, Scalp Ringworm'},
    {name:'SunGuard SPF50 Cream',sku:'MP-DV-007',category_id:4,sub_category:'Sun Protection',description:'Broad-spectrum UVA/UVB protection with PA+++ rating combining physical and chemical filters in a lightweight, water-resistant base.',composition:'Zinc Oxide 10% + Octinoxate 7.5% + Titanium Dioxide 5%',pack_size:'60g Tube',indication:'Photoprotection, Hyperpigmentation, Post-procedure Care'},
    {name:'UVShield Gel SPF30',sku:'MP-DV-008',category_id:4,sub_category:'Sun Protection',description:'Oil-free, matte-finish sunscreen gel for acne-prone and oily skin types for daily UV defence without pore-clogging.',composition:'Oxybenzone 4% + Octocrylene 7% + Niacinamide 2%',pack_size:'50g Tube',indication:'Daily Sun Protection, Oily/Acne-prone Skin'},
  ];

  let done = 0;
  products.forEach(p => {
    db.query('INSERT IGNORE INTO products SET ?', p, (err, r) => {
      if (err) console.log('ERR:', p.sku, err.message);
      else console.log('OK:', p.sku, 'id:', r.insertId);
      done++;
      if (done === products.length) { console.log('Done!'); process.exit(); }
    });
  });
});
